### ISSUE TITLE
Communciation problem between Synapse and LNet

### ISSUE THREAD

**Issue by han-k59** [pchev/alpaca_server#2]
Patrick,

Maybe you could help with an other problem. HNSKY is using Lnet (Lightweight Networking Library) for the TCP client. But it can't communicate with the Synapse server. After sending the first message the connection is dropped. The same problem occurred when I made a few days ago a server based on LNet. When CCdCiel connect the LNet server, the same disconnect occurs after the first GET ..../connection transmission.

Communicating between HNSKY using Lnet and AscomRemoverserver works without problems.

So somehow LNet and Synapse won't communicate. I can't find a setting in LNet to fix it. But the existing planetarium link between HNSKY from CCDCiel works.  So I'm wondering is there a magic setting in Synapse to fix this? What is the difference between the Planetarium link and an Alpaca link?

Thanks, Han

**Comment by pchev** [comment]
I implemented the server as HTTP/1.0 that not support persistent connection. 
So after every request the socket is closed and "Connection: close" is indicated in the header.

I think the ascom remote server implement HTTP/1.1 and you can specify "Connection: keep-alive" in the header, with timeout specified in the "Keep-alive:" header.

I not see a necessity to implement this timeout because alpaca rate is normally low, this is not the same as a web page that request hundreds of elements to complete the page.

**Comment by han-k59** [comment]
That makes sense. Thanks. :) The only thing I can't find, where do exactly you specify the timeout time?  I don't think it works like this:

`     result:='HTTP/1.1 200' + CRLF
             +'Connection: Keep-Alive' + CRLF
             +'Keep-Alive: timeout=300'+ CRLF
`

**Comment by pchev** [comment]
I not specify it, it is added by default in client connection by Synapse when the KeepAlive property is true. 

But maybe I was not clear enough, this alpaca server do not implement keep-alive, even if you specify it in the header. I always reply with  "Connection: close" in the response header and close the socket.
In this case the client must be prepared to create a new connection for the next request.

**Comment by han-k59** [comment]
I have build a new server with Synapse to get a clearer picture. That works but All examples i can find  assume a http/1.0 server which doesn't solve the disconnect.

In your code I can't find the keepalive property.

In the Synapse 4.0 code only for THTTPsend you can set FKeepAlive=true and FProtocol=1.1.  It looks like that only a http/1.1 server would fix my problem but THTTPsend is not used in your code. Could you give a hint if it is easy change to make a http/1.1 server or is that a large change?

Thanks, Han

**Comment by pchev** [comment]
Han,

I check again the Alpaca documentation and there is no requirement to support keep-alive.
So you must expect in the future that half of the Alpaca server will not support it, specifically the server embedded in the hardware using small SOC with very limited concurrent connection capability.

This is probably a big change for the server code. I can look later to implement that but for now I think it is best if you fix your client to support the disconnection.

**Comment by pchev** [comment]
In CCDciel it create a short lived thread for every Alpaca request. The thread do the http operation because Synapse use blocking socket, then the result is processed and the thread destroyed.
This is in cu_ascomrest.pas.

**Comment by han-k59** [comment]
Okay thanks, I will look to my HNSKY client and if I can fix it there or swap it for Synapse client. Hopefully it is not too much hassle.
